#!/usr/bin/env python3
"""Builds site/ from site-src/. Static output only — no client-side
framework, so Cloudflare Pages serves site/ with no build step configured on
its end. Run this locally after editing site-src/ and commit the result.

    python3 tools/build-site.py

Adding a language means adding one entry to LANGUAGES and one content dict
below; the page functions and layout are language-agnostic.
"""

from __future__ import annotations

import pathlib
import shutil

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE_SRC = REPO_ROOT / "site-src"
SITE_OUT = REPO_ROOT / "site"

# ---------------------------------------------------------------------------
# Languages. English is canonical and lives at the site root; every other
# language gets a /<code>/ prefix, mirroring docs/install.md · install.nl.md
# · install.fr.md elsewhere in this repo.
# ---------------------------------------------------------------------------

LANGUAGES = ["en", "nl", "fr"]
LANG_NAMES = {"en": "English", "nl": "Nederlands", "fr": "Français"}


def lang_prefix(lang: str) -> str:
    return "" if lang == "en" else f"/{lang}"


# ---------------------------------------------------------------------------
# Shared chrome: nav, footer, language switcher.
# ---------------------------------------------------------------------------

NAV = {
    "en": {"home": "Home", "faq": "Q&A", "install": "Install", "github": "GitHub"},
    "nl": {"home": "Home", "faq": "Q&A", "install": "Installeren", "github": "GitHub"},
    "fr": {"home": "Accueil", "faq": "Q&A", "install": "Installer", "github": "GitHub"},
}

FOOTER = {
    "en": "Drawbridge is free and open source (MIT).",
    "nl": "Drawbridge is gratis en open source (MIT).",
    "fr": "Drawbridge est gratuit et open source (MIT).",
}
FOOTER_SOURCE = {"en": "Source on GitHub", "nl": "Broncode op GitHub", "fr": "Code source sur GitHub"}


def render_page(
    *,
    lang: str,
    path: str,
    title: str,
    description: str,
    body: str,
    lang_switch_targets: dict[str, str] | None = None,
) -> str:
    """path is the page's own path relative to its language root, e.g. '', 'faq/', 'install/'.

    why-blocked/ is a single English-only page (no point translating ~200
    cited rows into languages nobody has reviewed the legal claims in), so
    every language's nav links to the same canonical /why-blocked/ URL
    rather than a per-language prefix that would not exist.
    """
    prefix = lang_prefix(lang)
    nav = NAV[lang]

    def nav_link(target_path: str, label: str, *, href: str | None = None) -> str:
        resolved = href if href is not None else (f"{prefix}/{target_path}" if target_path else (prefix or "/"))
        active = " aria-current=\"page\"" if target_path == path else ""
        return f'<a href="{resolved}"{active}>{label}</a>'

    nav_html = "\n      ".join([
        nav_link("", nav["home"]),
        nav_link("faq/", nav["faq"]),
        nav_link("install/", nav["install"]),
        f'<a href="https://github.com/Nilss3/drawbridge">{nav["github"]}</a>',
    ])

    switcher_links = []
    for code in LANGUAGES:
        if lang_switch_targets is not None:
            href = lang_switch_targets[code]
        else:
            target_prefix = lang_prefix(code)
            href = f"{target_prefix}/{path}" if path else (target_prefix or "/")
        current = " class=\"lang-current\"" if code == lang else ""
        switcher_links.append(f'<a href="{href}"{current}>{code.upper()}</a>')
    switcher_html = " · ".join(switcher_links)

    home_href = prefix or "/"
    return f"""<!doctype html>
<html lang="{lang}">
<head>
<!-- Generated by tools/build-site.py from site-src/. Do not hand-edit — rerun the build script instead. -->
<meta charset="utf-8" />
<title>{title}</title>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="description" content="{description}" />
<link rel="icon" href="/assets/img/icon.webp" />
<link rel="stylesheet" href="/assets/css/style.css" />
</head>
<body>
<header class="site-header">
  <div class="wrap">
    <a class="brand" href="{home_href}">
      <img src="/assets/img/icon.webp" alt="" />
      drawbridge
    </a>
    <div class="header-right">
      <nav class="nav">
      {nav_html}
      </nav>
      <div class="lang-switch">{switcher_html}</div>
    </div>
  </div>
</header>

<main>
{body}
</main>

<footer class="site-footer">
  <div class="wrap">
    <span>{FOOTER[lang]}</span>
    <span><a href="https://github.com/Nilss3/drawbridge">{FOOTER_SOURCE[lang]}</a></span>
  </div>
</footer>
</body>
</html>
"""


def steps_html(items: list[str], start: int = 1) -> str:
    lis = []
    for i, item in enumerate(items, start=start):
        lis.append(f'<li><span class="num">{i}</span><div>{item}</div></li>')
    attr = f' start="{start}"' if start != 1 else ""
    return f'<ol class="steps"{attr}>\n' + "\n".join(lis) + "\n</ol>"


# ---------------------------------------------------------------------------
# Homepage content
# ---------------------------------------------------------------------------

HOME = {
    "en": dict(
        title="drawbridge — protect your Android device from harmful content",
        description="A free, open-source, watertight content filter for Android. For yourself, or for a device you manage on someone else's behalf. No account, no backend, no telemetry.",
        beta="Slowly entering public beta. If it holds up, this site gets a real domain.",
        h1="Welcome to the drawbridge project",
        lede="Drawbridge protects you and your Android device from harmful content, so you can keep your focus and sanity.",
        p1='Make your phone a drawbridge phone: a phone clear of social media and other harmful time-wasters. A drawbridge phone can be used for yourself, and/or for your teenager, as a free, better and low-maintenance alternative to parental controls. The protection is based on the best practices of digital minimalism and supported by neuroscience and parents\' organisations. Drawbridge is free, open source, no frills, watertight, and respects your privacy. No account is needed, and none of your data is ever uploaded.',
        p2='Drawbridge is a protection on your device which "raises the bridge" to harmful content and keeps it from entering your device, your life and your soul. It stops adult content, gambling, ads, algorithmic social media, AI companions, and exploitative games.',
        browser_teaser='The project also includes herald, a browser you can download and use on its own — <a href="#herald">see below</a>.',
        cta_primary="Get started",
        cta_secondary="See what's blocked, and why",
        how_h2="How it works",
        how_p1='You\'ll need to start from a fresh device or a factory reset. During the usual set-up, you need to scan a QR code or use a button on this website. This will embed drawbridge on your device. Once installed, just start it. You\'ll get a random code to deactivate drawbridge. Alternatively, "forget" the code and have your protection indefinitely.',
        how_p2="Drawbridge relies on a web filter, a block list, and a custom browser. You don't need an account, and no data leaves your device. As opposed to parental controls or app blockers, there is little to no configuration, it already has everything there to protect you. There is also no workaround.",
        how_art_alt="A phone with a raised drawbridge across its screen: a calm green landscape inside, dark creatures shut out behind it.",
        how_cta_faq="Read the Q&amp;A",
        how_cta_install="Installation guide",
        devices_h2="On what devices?",
        devices_intro="Drawbridge should work on <strong>all Android devices</strong> running near-stock Android, or with good enterprise support.",
        good_title="Should work well",
        good_text="Samsung, Motorola, OnePlus, Nothing Phone, Fairphone, Sony, Nokia/HMD, and many more.",
        warn_title="May not be supported",
        warn_text="Devices with heavily modified Android: Xiaomi, Oppo, Vivo, Redmi, Realme.",
        see_faq="See our Q&amp;A",
        browser_h2="The herald browser",
        herald_intro='herald (as in "messenger, harbinger" who can cross the bridge) is a browser custom made for drawbridge, but is also available as a stand-alone app for everyone to use. It is especially interesting for people who already have parental controls or app blockers in place, but find that the browser remains a necessity which can bypass restrictions and is otherwise also an unwanted time waster. Those people can install herald as their one and only browser.',
        herald_is_lead="The herald browser is:",
        herald_bullets=[
            "Based on Firefox",
            "Blocks harmful content combining the same public and custom blocklists as drawbridge",
            "Allows no extensions (this could circumvent the block) but it does have uBlock Origin installed",
            "Has a reader mode, dark mode, etc.",
        ],
        mono_intro='herald mono is another version of this browser, especially for people who find browsing the internet itself addictive (news, shopping, etc.). It is inspired by e-ink screens and the Firefox Focus browser to make browsing less enticing:',
        mono_bullets=[
            "It renders everything in black and white",
            'It opens webpages by default in reader mode when possible<ul><li>You can still choose to see a specific page in normal mode or in color if you need for various reasons (e.g. you need to read a colorful graph in a news article)</li></ul>',
            "There are no tabs. Single-tasking it is.",
            "There is a breathing pause every time you open a webpage.",
        ],
        browsers_outro="The browsers may be downloaded as packages from the repo directly. In the future we may foresee an entry in the Play Store.",
        browsers_cta="Download the latest release",
    ),
    "nl": dict(
        title="drawbridge — bescherm je Android-toestel tegen schadelijke inhoud",
        description="Een gratis, open source, waterdichte contentfilter voor Android. Voor jezelf, of voor een toestel dat je voor iemand anders beheert. Geen account, geen backend, geen telemetrie.",
        beta="Stapsgewijs in publieke beta. Als het goed werkt, krijgt deze site een echt domein.",
        h1="Welkom bij het drawbridge-project",
        lede="Drawbridge beschermt jou en je Android-toestel tegen schadelijke inhoud, zodat je je focus en gemoedsrust behoudt.",
        p1='Maak van je telefoon een drawbridge-telefoon: een telefoon vrij van social media en andere schadelijke tijdverspillers. Een drawbridge-telefoon kan gebruikt worden voor jezelf, en/of voor je tiener, als een gratis, betere en onderhoudsarme alternatief voor parental controls. De bescherming is gebaseerd op de beste praktijken van digitaal minimalisme en wordt ondersteund door neurowetenschap en ouderverenigingen. Drawbridge is gratis, open source, zonder franjes, waterdicht, en respecteert je privacy. Er is geen account nodig, en er wordt nooit data geüpload.',
        p2='Drawbridge is een bescherming op je toestel die "de brug ophaalt" voor schadelijke inhoud en verhindert dat die je toestel, je leven en je ziel binnendringt. Het houdt pornografie, gokken, advertenties, algoritmische social media, AI companions en uitbuitende games tegen.',
        browser_teaser='Het project omvat ook herald, een browser die je apart kan downloaden en gebruiken — <a href="#herald">zie hieronder</a>.',
        cta_primary="Aan de slag",
        cta_secondary="Bekijk wat geblokkeerd wordt, en waarom",
        how_h2="Hoe het werkt",
        how_p1='Je hebt een vers toestel nodig, of een factory reset. Tijdens de gewone installatie scan je een QR-code, of gebruik je een knop op deze website. Dat installeert drawbridge op je toestel. Eenmaal geïnstalleerd, start je het gewoon op. Je krijgt een willekeurige code om drawbridge te deactiveren. Je kan die code ook bewust "vergeten", zodat je bescherming voor onbepaalde tijd actief blijft.',
        how_p2="Drawbridge steunt op een webfilter, een blocklist, en een eigen browser. Je hebt geen account nodig, en er wordt nooit data van je toestel verzonden. In tegenstelling tot parental controls of app blockers is er nauwelijks tot geen configuratie nodig — alles staat er al klaar om je te beschermen. Er is ook geen workaround.",
        how_art_alt="Een telefoon met een opgehaalde brug over het scherm: een rustig groen landschap binnenin, duistere wezens buitengesloten.",
        how_cta_faq="Lees de Q&amp;A",
        how_cta_install="Installatiegids",
        devices_h2="Op welke toestellen?",
        devices_intro="Drawbridge zou moeten werken op <strong>alle Android-toestellen</strong> met een bijna-stock Android, of met goede enterprise-ondersteuning.",
        good_title="Zou goed moeten werken",
        good_text="Samsung, Motorola, OnePlus, Nothing Phone, Fairphone, Sony, Nokia/HMD, en vele andere.",
        warn_title="Mogelijk niet ondersteund",
        warn_text="Toestellen met sterk aangepaste Android-versies: Xiaomi, Oppo, Vivo, Redmi, Realme.",
        see_faq="Bekijk onze Q&amp;A",
        browser_h2="De herald-browser",
        herald_intro='herald (zoals in "boodschapper, heraut" die de brug mag oversteken) is een browser speciaal gemaakt voor drawbridge, maar is ook beschikbaar als losstaande app voor iedereen. Hij is vooral interessant voor mensen die al parental controls of app blockers gebruiken, maar merken dat de browser een noodzaak blijft die restricties kan omzeilen en anders ook een ongewenste tijdverspiller is. Die mensen kunnen herald installeren als hun enige browser.',
        herald_is_lead="De herald-browser:",
        herald_bullets=[
            "Is gebaseerd op Firefox",
            "Blokkeert schadelijke inhoud met dezelfde publieke en aangepaste blocklists als drawbridge",
            "Laat geen extensies toe (dit zou de blokkade kunnen omzeilen), maar heeft wel uBlock Origin geïnstalleerd",
            "Heeft een leesmodus, donkere modus, enz.",
        ],
        mono_intro='herald mono is een andere versie van deze browser, speciaal voor mensen die het surfen op internet zelf verslavend vinden (nieuws, online shoppen, enz.). Het is geïnspireerd op e-inktschermen en de Firefox Focus-browser, om browsen minder aanlokkelijk te maken:',
        mono_bullets=[
            "Toont alles in zwart-wit",
            'Opent webpagina\'s standaard in leesmodus wanneer mogelijk<ul><li>Je kan nog steeds kiezen om een specifieke pagina in normale modus of in kleur te bekijken, indien nodig (bv. om een kleurrijke grafiek in een nieuwsartikel te lezen)</li></ul>',
            "Er zijn geen tabbladen. Singletasking dus.",
            "Er is een ademhalingspauze telkens je een webpagina opent.",
        ],
        browsers_outro="De browsers kunnen rechtstreeks als pakket gedownload worden vanuit de repo. In de toekomst overwegen we mogelijk een vermelding in de Play Store.",
        browsers_cta="Download de laatste release",
    ),
    "fr": dict(
        title="drawbridge — protégez votre appareil Android des contenus nuisibles",
        description="Un filtre de contenu gratuit, open source et étanche pour Android. Pour vous-même, ou pour un appareil que vous gérez pour quelqu'un d'autre. Pas de compte, pas de serveur, aucune télémétrie.",
        beta="En bêta publique progressive. Si tout se passe bien, ce site aura son propre nom de domaine.",
        h1="Bienvenue sur le projet drawbridge",
        lede="Drawbridge protège votre appareil Android des contenus nuisibles, pour préserver votre concentration et votre équilibre.",
        p1='Faites de votre téléphone un téléphone drawbridge : un téléphone débarrassé des réseaux sociaux et autres pertes de temps nuisibles. Un téléphone drawbridge peut être utilisé pour vous-même, et/ou pour votre adolescent, comme alternative gratuite, meilleure et peu contraignante aux contrôles parentaux. La protection s\'appuie sur les meilleures pratiques du minimalisme numérique et est soutenue par les neurosciences et des associations de parents. Drawbridge est gratuit, open source, sans fioritures, étanche, et respecte votre vie privée. Aucun compte n\'est nécessaire, et aucune de vos données n\'est jamais transmise.',
        p2='Drawbridge est une protection sur votre appareil qui « relève le pont-levis » face aux contenus nuisibles et les empêche d\'entrer dans votre appareil, votre vie et votre âme. Elle bloque les contenus pour adultes, les jeux d\'argent, la publicité, les réseaux sociaux algorithmiques, les compagnons IA et les jeux d\'exploitation.',
        browser_teaser='Le projet comprend aussi herald, un navigateur que vous pouvez télécharger et utiliser séparément — <a href="#herald">voir plus bas</a>.',
        cta_primary="Commencer",
        cta_secondary="Voir ce qui est bloqué, et pourquoi",
        how_h2="Comment ça marche",
        how_p1="Il vous faut un appareil neuf, ou une réinitialisation aux paramètres d'usine. Lors de la configuration habituelle, vous scannez un QR code, ou utilisez un bouton sur ce site. Cela installe drawbridge sur votre appareil. Une fois installé, il suffit de le démarrer. Vous recevrez un code aléatoire pour désactiver drawbridge. Vous pouvez aussi « oublier » ce code volontairement, pour que la protection reste active indéfiniment.",
        how_p2="Drawbridge s'appuie sur un filtre web, une liste de blocage, et un navigateur dédié. Aucun compte n'est nécessaire, et aucune donnée ne quitte votre appareil. Contrairement aux contrôles parentaux ou aux bloqueurs d'applications, il n'y a que peu, voire aucune configuration à faire — tout est déjà en place pour vous protéger. Il n'existe pas non plus de moyen de contournement.",
        how_art_alt="Un téléphone dont le pont-levis est relevé sur l'écran : un paysage vert et calme à l'intérieur, des créatures sombres tenues à l'écart.",
        how_cta_faq="Lire la Q&amp;A",
        how_cta_install="Guide d'installation",
        devices_h2="Sur quels appareils ?",
        devices_intro="Drawbridge devrait fonctionner sur <strong>tous les appareils Android</strong> proches d'Android stock, ou bénéficiant d'un bon support entreprise.",
        good_title="Devrait bien fonctionner",
        good_text="Samsung, Motorola, OnePlus, Nothing Phone, Fairphone, Sony, Nokia/HMD, et bien d'autres.",
        warn_title="Support non garanti",
        warn_text="Appareils avec une version d'Android fortement modifiée : Xiaomi, Oppo, Vivo, Redmi, Realme.",
        see_faq="Consultez notre Q&amp;A",
        browser_h2="Le navigateur herald",
        herald_intro='herald (comme dans « messager, héraut » qui peut traverser le pont) est un navigateur conçu spécialement pour drawbridge, mais aussi disponible comme application autonome pour tout le monde. Il est particulièrement utile pour les personnes qui ont déjà un contrôle parental ou un bloqueur d\'applications en place, mais constatent que le navigateur reste un point de passage nécessaire qui peut contourner ces restrictions, et qui est par ailleurs une perte de temps non désirée. Ces personnes peuvent installer herald comme unique navigateur.',
        herald_is_lead="Le navigateur herald :",
        herald_bullets=[
            "Basé sur Firefox",
            "Bloque les contenus nuisibles en combinant les mêmes listes de blocage publiques et personnalisées que drawbridge",
            "N'autorise aucune extension (cela pourrait contourner le blocage), mais il a bien uBlock Origin installé",
            "Dispose d'un mode lecture, d'un mode sombre, etc.",
        ],
        mono_intro="herald mono est une autre version de ce navigateur, spécialement pour les personnes qui trouvent que naviguer sur internet est en soi addictif (actualités, achats en ligne, etc.). Il s'inspire des écrans à encre électronique et du navigateur Firefox Focus pour rendre la navigation moins attrayante :",
        mono_bullets=[
            "Il affiche tout en noir et blanc",
            "Il ouvre les pages web par défaut en mode lecture, quand c'est possible<ul><li>Vous pouvez toujours choisir d'afficher une page précise en mode normal ou en couleur si besoin (par exemple pour lire un graphique coloré dans un article de presse)</li></ul>",
            "Il n'y a pas d'onglets. Une seule tâche à la fois.",
            "Il y a une pause de respiration à chaque ouverture d'une page web.",
        ],
        browsers_outro="Les navigateurs peuvent être téléchargés directement sous forme de paquets depuis le dépôt. À l'avenir, une présence sur le Play Store est envisagée.",
        browsers_cta="Télécharger la dernière version",
    ),
}


def render_home(lang: str) -> str:
    c = HOME[lang]
    prefix = lang_prefix(lang)
    install_href = f"{prefix}/install/"
    faq_href = f"{prefix}/faq/"
    why_href = f"{prefix}/why-blocked/"

    herald_bullets_html = "\n".join(f"<li>{item}</li>" for item in c["herald_bullets"])
    mono_bullets_html = "\n".join(f"<li>{item}</li>" for item in c["mono_bullets"])

    body = f"""
  <section class="hero">
    <div class="wrap">
      <span class="beta-note">{c['beta']}</span>
      <h1>{c['h1']}</h1>
      <p class="lede">{c['lede']}</p>
      <div class="hero-art">
        <picture>
          <source srcset="/assets/img/hero-night.webp" media="(prefers-color-scheme: dark)" />
          <img src="/assets/img/hero.webp" alt="" />
        </picture>
      </div>
      <p>{c['p1']}</p>
      <p>{c['p2']}</p>
      <p>{c['browser_teaser']}</p>
      <div class="btn-row">
        <a class="btn btn--primary" href="{install_href}">{c['cta_primary']}</a>
        <a class="btn btn--ghost" href="{why_href}">{c['cta_secondary']}</a>
      </div>
    </div>
  </section>

  <section class="section section--alt">
    <div class="wrap">
      <h2>{c['how_h2']}</h2>
      <div class="how-grid">
        <div>
          <p>{c['how_p1']}</p>
          <p>{c['how_p2']}</p>
          <div class="btn-row" style="margin-bottom:0;">
            <a class="btn btn--ghost" href="{faq_href}">{c['how_cta_faq']}</a>
            <a class="btn btn--ghost" href="{install_href}">{c['how_cta_install']}</a>
          </div>
        </div>
        <div class="how-art">
          <img src="/assets/img/howitworks.webp" alt="{c['how_art_alt']}" />
        </div>
      </div>
    </div>
  </section>

  <section class="section">
    <div class="wrap">
      <h2>{c['devices_h2']}</h2>
      <p>{c['devices_intro']}</p>
      <div class="device-lists">
        <div class="card card--good">
          <h3>{c['good_title']}</h3>
          <p>{c['good_text']}</p>
        </div>
        <div class="card card--warn">
          <h3>{c['warn_title']}</h3>
          <p>{c['warn_text']}</p>
        </div>
      </div>
      <div class="btn-row">
        <a class="btn btn--ghost" href="{faq_href}">{c['see_faq']}</a>
      </div>
    </div>
  </section>

  <section class="section section--alt" id="herald">
    <div class="wrap">
      <h2>{c['browser_h2']}</h2>
      <p>{c['herald_intro']}</p>

      <div class="browser-card">
        <div class="browser-card-head">
          <img src="/assets/img/herald-icon.webp" alt="" class="browser-card-icon" />
          <h3>herald</h3>
        </div>
        <p>{c['herald_is_lead']}</p>
        <ul>
{herald_bullets_html}
        </ul>
      </div>

      <div class="browser-card">
        <div class="browser-card-head">
          <img src="/assets/img/herald-mono-icon.webp" alt="" class="browser-card-icon" />
          <h3>herald mono</h3>
        </div>
        <p>{c['mono_intro']}</p>
        <ul>
{mono_bullets_html}
        </ul>
      </div>

      <p>{c['browsers_outro']}</p>
      <div class="btn-row">
        <a class="btn btn--primary" href="https://github.com/Nilss3/drawbridge/releases/latest">{c['browsers_cta']}</a>
      </div>
    </div>
  </section>
"""
    return render_page(
        lang=lang,
        path="",
        title=c["title"],
        description=c["description"],
        body=body,
    )


# ---------------------------------------------------------------------------
# Install page content
# ---------------------------------------------------------------------------

INSTALL = {
    "en": dict(
        title="Install — drawbridge",
        description="How to install drawbridge: scan the QR code, or use the USB fallback if the QR code doesn't work on your device.",
        h1="Installing drawbridge",
        lede="One of two paths, depending on whether your device's setup wizard offers a QR scanner.",
        alpha_warning="This is still in early alpha testing!!",
        alpha_detail="Provisioning has not yet been confirmed working on a real phone. Expect it to fail, and do not use a device you depend on.",
        qr_h2="The standard way: QR code",
        qr_caption="Scan this code during set-up.",
        qr_alt="The drawbridge provisioning QR code.",
        qr_steps=[
            "<strong>Start from a fresh device, or do a factory reset.</strong> Back up your data first, since a reset wipes it.",
            "On the welcome screen, tap the same spot <strong>6 times</strong> to reveal a hidden QR scanner.",
            "Scan the drawbridge QR code.",
            "Wait for setup to finish — the device downloads, verifies and installs everything on its own.",
        ],
        fallback_h2="If the QR code doesn't work",
        fallback_intro="Some devices ship a setup wizard without the six-tap gesture, or skip the QR scanner entirely. There is a second way in, over USB, that works regardless.",
        fallback_steps=[
            "Continue through setup, but <strong>don't sign in to any account</strong> — skip that step. This matters: the installer needs a device with no account yet configured.",
            "Enable Developer Options (tap the build number in Settings → About phone several times) and turn on <strong>USB debugging</strong>.",
            "Connect your device to a computer with a USB cable, and use the installer below.",
            "Wait for setup to finish.",
        ],
        coming_title="Browser-based installer — coming soon",
        coming_text="A page here will let you install drawbridge straight from a Chromium-based browser (Chrome, Edge) over USB — no separate software to install. It isn't ready yet.",
        coming_btn="Install over USB — coming soon",
        meanwhile="In the meantime, technically comfortable users can grant drawbridge the same access using Android's own <code>adb</code> developer tool from a computer, on a device with no account signed in yet.",
        after_h2="After setup",
        after_steps=[
            "Open the drawbridge app and activate it.",
            "Write down the deactivation code shown once — or don't, if you want the protection to stay on for good.",
        ],
        see_more='Read the <a href="{faq}">Q&amp;A</a> for what\'s blocked and why, or see the <a href="{why}">full sourced breakdown</a>.',
    ),
    "nl": dict(
        title="Installeren — drawbridge",
        description="Hoe je drawbridge installeert: scan de QR-code, of gebruik de USB-methode als de QR-code niet werkt op je toestel.",
        h1="Drawbridge installeren",
        lede="Twee mogelijke paden, afhankelijk van of de installatiewizard van je toestel een QR-scanner aanbiedt.",
        alpha_warning="Dit zit nog volop in vroege alfatesting!!",
        alpha_detail="Het uitrollen is nog niet bevestigd op een echte telefoon. Ga ervan uit dat het kan mislukken, en gebruik geen toestel waar je van afhangt.",
        qr_h2="De standaardmanier: QR-code",
        qr_caption="Scan deze code tijdens de installatie.",
        qr_alt="De drawbridge-QR-code voor installatie.",
        qr_steps=[
            "<strong>Begin met een vers toestel, of doe een factory reset.</strong> Maak eerst een back-up van je data, want een reset wist alles.",
            "Tik op het welkomstscherm <strong>6 keer</strong> op dezelfde plek om een verborgen QR-scanner tevoorschijn te halen.",
            "Scan de drawbridge-QR-code.",
            "Wacht tot de installatie is afgerond — het toestel downloadt, verifieert en installeert alles zelf.",
        ],
        fallback_h2="Als de QR-code niet werkt",
        fallback_intro="Sommige toestellen hebben een installatiewizard zonder de zes-tik-gebaar, of slaan de QR-scanner helemaal over. Er is een alternatieve weg naar binnen, via USB, die altijd werkt.",
        fallback_steps=[
            "Doorloop de installatie, maar <strong>meld je nog niet aan met een account</strong> — sla die stap over. Dit is belangrijk: de installer heeft een toestel nodig waarop nog geen account is ingesteld.",
            "Activeer Ontwikkelaarsopties (tik meerdere keren op het buildnummer in Instellingen → Over de telefoon) en schakel <strong>USB-debugging</strong> in.",
            "Verbind je toestel met een computer via een USB-kabel, en gebruik de installer hieronder.",
            "Wacht tot de installatie is afgerond.",
        ],
        coming_title="Browsergebaseerde installer — binnenkort beschikbaar",
        coming_text="Hier komt een pagina waarmee je drawbridge rechtstreeks vanuit een Chromium-browser (Chrome, Edge) via USB kan installeren — geen aparte software nodig. Deze is nog niet klaar.",
        coming_btn="Installeren via USB — binnenkort",
        meanwhile="Ondertussen kunnen technisch onderlegde gebruikers drawbridge dezelfde toegang geven via Android's eigen <code>adb</code>-ontwikkelaarstool vanaf een computer, op een toestel waarop nog geen account is aangemeld.",
        after_h2="Na de installatie",
        after_steps=[
            "Open de drawbridge-app en activeer ze.",
            "Schrijf de eenmalig getoonde deactivatiecode op — of niet, als je wil dat de bescherming voorgoed aanblijft.",
        ],
        see_more='Lees de <a href="{faq}">Q&amp;A</a> voor wat er geblokkeerd wordt en waarom, of bekijk het <a href="{why}">volledige, onderbouwde overzicht</a>.',
    ),
    "fr": dict(
        title="Installation — drawbridge",
        description="Comment installer drawbridge : scannez le QR code, ou utilisez la méthode USB si le QR code ne fonctionne pas sur votre appareil.",
        h1="Installer drawbridge",
        lede="Deux méthodes possibles, selon que l'assistant de configuration de votre appareil propose ou non un lecteur de QR code.",
        alpha_warning="Ceci est encore en phase de test alpha !!",
        alpha_detail="Le déploiement n'a pas encore été confirmé sur un vrai téléphone. Attendez-vous à ce que cela échoue, et n'utilisez pas un appareil dont vous dépendez.",
        qr_h2="La méthode standard : QR code",
        qr_caption="Scannez ce code pendant la configuration.",
        qr_alt="Le QR code d'installation de drawbridge.",
        qr_steps=[
            "<strong>Partez d'un appareil neuf, ou faites une réinitialisation aux paramètres d'usine.</strong> Sauvegardez d'abord vos données, car une réinitialisation efface tout.",
            "Sur l'écran d'accueil, tapez <strong>6 fois</strong> au même endroit pour révéler un lecteur de QR code caché.",
            "Scannez le QR code de drawbridge.",
            "Attendez la fin de l'installation — l'appareil télécharge, vérifie et installe tout automatiquement.",
        ],
        fallback_h2="Si le QR code ne fonctionne pas",
        fallback_intro="Certains appareils ont un assistant de configuration sans le geste des 6 tapotements, ou ignorent complètement le lecteur de QR code. Il existe une seconde voie, par USB, qui fonctionne dans tous les cas.",
        fallback_steps=[
            "Poursuivez la configuration, mais <strong>ne vous connectez à aucun compte</strong> — passez cette étape. C'est important : l'installeur a besoin d'un appareil sans compte configuré.",
            "Activez les options pour développeurs (tapez plusieurs fois sur le numéro de build dans Paramètres → À propos du téléphone) et activez le <strong>débogage USB</strong>.",
            "Connectez votre appareil à un ordinateur avec un câble USB, et utilisez l'installeur ci-dessous.",
            "Attendez la fin de l'installation.",
        ],
        coming_title="Installeur dans le navigateur — bientôt disponible",
        coming_text="Une page ici vous permettra d'installer drawbridge directement depuis un navigateur basé sur Chromium (Chrome, Edge) par USB — sans logiciel séparé à installer. Ce n'est pas encore prêt.",
        coming_btn="Installer via USB — bientôt disponible",
        meanwhile="En attendant, les utilisateurs à l'aise avec la technique peuvent accorder à drawbridge le même accès grâce à l'outil de développement <code>adb</code> d'Android, depuis un ordinateur, sur un appareil sans compte encore connecté.",
        after_h2="Après l'installation",
        after_steps=[
            "Ouvrez l'application drawbridge et activez-la.",
            "Notez le code de désactivation affiché une seule fois — ou pas, si vous voulez que la protection reste active pour de bon.",
        ],
        see_more='Consultez la <a href="{faq}">Q&amp;A</a> pour savoir ce qui est bloqué et pourquoi, ou voir le <a href="{why}">détail complet sourcé</a>.',
    ),
}


def render_install(lang: str) -> str:
    c = INSTALL[lang]
    prefix = lang_prefix(lang)
    faq_href = f"{prefix}/faq/"
    why_href = f"{prefix}/why-blocked/"

    body = f"""
  <section class="section">
    <div class="wrap">
      <h1>{c['h1']}</h1>
      <p class="lede">{c['lede']}</p>

      <div class="callout callout--alpha">
        <strong>{c['alpha_warning']}</strong>
        <p style="margin: 0.5rem 0 0;">{c['alpha_detail']}</p>
      </div>

      <h2>{c['qr_h2']}</h2>
      {steps_html(c['qr_steps'])}

      <figure class="qr-figure">
        <img src="/assets/img/provisioning-qr.png" alt="{c['qr_alt']}" width="776" height="776" />
        <figcaption>{c['qr_caption']}</figcaption>
      </figure>

      <h2>{c['fallback_h2']}</h2>
      <p>{c['fallback_intro']}</p>
      {steps_html(c['fallback_steps'])}

      <div class="callout callout--coming-soon">
        <strong>{c['coming_title']}</strong>
        <p style="margin: 0.6rem 0 0;">{c['coming_text']}</p>
        <div class="btn-row" style="margin-bottom:0;">
          <span class="btn btn--disabled">{c['coming_btn']}</span>
        </div>
      </div>

      <p class="footnote">{c['meanwhile']}</p>

      <h2>{c['after_h2']}</h2>
      {steps_html(c['after_steps'], start=5)}

      <p>{c['see_more'].format(faq=faq_href, why=why_href)}</p>
    </div>
  </section>
"""
    return render_page(lang=lang, path="install/", title=c["title"], description=c["description"], body=body)


# ---------------------------------------------------------------------------
# FAQ content. Dutch is the source (as originally written); English and
# French are translations, kept faithful rather than loose, since the
# subject matter (grooming, cyberbullying, addiction mechanics) is not the
# place for paraphrase.
# ---------------------------------------------------------------------------

FAQ = {
    "en": dict(
        title="Q&A — drawbridge",
        description="Frequently asked questions about drawbridge: what's blocked, who it's for, and how it compares to ordinary parental controls.",
        h1="Q&A",
        blocks=[
            ("h2", "Which apps and websites are blocked?"),
            ("p", 'To protect your wellbeing and your device, drawbridge blocks the following categories: porn, gambling, scams, algorithmic social media, AI companions, and games with addictive mechanics or grooming risk. Some social media is genuinely debatable: Reddit and Discord, for instance, have strong community moderation in places, but they also still host a lot of extreme gore content and toxic comments. Either way, sites like that are better visited on a PC. There is no reason to carry them around in your pocket.'),
            ("p", 'Everything else works normally: tools, office apps, weather, banking, public transport, school, work, and so on.'),

            ("h2", "Who is drawbridge for?"),
            ("p", "Drawbridge is for anyone who needs to carry a smartphone but doesn't want that phone to make room or time for harmful and addictive apps and websites. That can be an adult protecting themselves, or someone managing another person's device (a child, for instance)."),

            ("h2", "Why not just use parental controls or an app blocker?"),
            ("p", "Parental controls have a lot of downsides:"),
            ("ul", [
                "They are hard to configure, and there is always some new adjustment to make.",
                "You have to build up expertise in everything that is harmful and everything that can be configured. That is just wasted time.",
                "They are easy to bypass, even when well configured.",
                "They lead to arguments and conflict, between parent and child, or within yourself.",
                "They spy on the user and may collect data.",
                "They are often not free.",
            ]),
            ("p", 'Drawbridge does not use parental controls at all; it is a device policy controller, the kind used for company phones and kiosks. Unlike parental controls, drawbridge ships out of the box with non-configurable protection that already gives very broad coverage. Social media and harmful games are always blocked, no argument about it. That creates an environment of calm without extra overhead. Be aware that drawbridge alone is not enough as "online guidance for a child". A lot more goes into that, and one best practice remains using the internet on a shared screen, where everyone can see and talk about what is happening (not for private conversations, of course).'),

            ("h2", "How can I turn off or bypass drawbridge?"),
            ("p", "Drawbridge has both a network filter and an on-device filter, and is therefore about as watertight as it gets. Still, there are plenty of websites and apps that will occasionally show something harmful. Don't hesitate to report it. The classic back door, the browser, is sealed too, and drawbridge offers its own take on browsing (see below)."),
            ("p", "After setting up drawbridge, a code is shown that lifts the filter and can remove drawbridge. The code is random and too long to memorise at a glance. The choice is yours: write it down and keep it somewhere safe, or don't write it down and forget it, in which case drawbridge stays active forever."),
            ("p", "The only other way out, which is also true for ordinary app blockers, is of course a factory reset. That resets the entire device and loses your data with it, effectively the same as buying a new phone. Still: if you manage the device for someone else, such as your child, and the device has a Google account on it, a factory reset requires the Google password. That is a safeguard against exactly this. The drawbridge app also shows the moment of last activation, an extra manual check to see that nothing was reset."),

            ("h2", "What about WhatsApp and other chat apps?"),
            ("p", 'Facebook Messenger and Telegram are blocked. WhatsApp is blocked by default too, since it increasingly resembles social media (channels, a chatbot). Because WhatsApp is a practical necessity for many people (in some countries people barely make ordinary phone calls anymore), you can choose to allow it anyway. Other chat apps such as Signal, Threema, Session, Briar and so on are allowed, because encrypted communication is a human right. If you are handing the device to a child, know that children under 14 struggle a great deal with group chats, which very quickly turn into cyberbullying and drama.'),

            ("h2", "What about YouTube?"),
            ("p", 'YouTube is, in effect, social media. Although its content is strictly moderated against extremes like nudity, gambling and violence, a lot of harmful or misleading content remains. YouTube serves everything in a highly addictive way, for which Google has already been held accountable in court. The most harmful part of all is YouTube Shorts, which is very hard to distinguish from ordinary YouTube videos and cannot be filtered without either violating privacy or relying on error-prone AI. Because YouTube is so pervasive as a "video library" full of genuinely useful information (cooking, DIY, and so on), a toggle similar to the WhatsApp one is being considered, though nothing is decided yet.'),

            ("h2", "Why aren't chatbots blocked?"),
            ("p", "Regular chatbots such as ChatGPT, Claude or Gemini can indeed have harmful effects on the brain with excessive use and by replacing cognitively demanding tasks. They are not built with addictive mechanisms, and, much like search engines, increasingly strict guardrails are appearing for certain kinds of questions. The bigger problem, though, is how pervasive chatbots have become: nearly every website or service now has some kind of \"assistant\" you can ask almost anything. If you don't want that, the honest answer is not to use the internet at all."),

            ("h2", "What about the browser?"),
            ("p", "The browser is traditionally the back door through which harmful content reaches your device and your life. A number of browsers and extensions are able to set up a proxy or VPN specifically to bypass the device's settings (often for perfectly good reasons elsewhere, but not here). Drawbridge therefore refuses every browser except herald. Herald is a browser built specifically for drawbridge, though it can also be downloaded on its own, and it blocks the same content as drawbridge by default, out of the box, no configuration needed. A variant, herald mono, is a browser built specifically for digital minimalism: it shows every website in black and white, has no tabs (single-tasking only), and opens everything in reader mode when available. That second browser is especially useful for people who feel they lose too much time to, say, news sites or online shopping."),
            ("p", "Under consideration, though not decided, is adding more browsers to the allowed list, ideally including a Chromium-based one for sites that don't work well in Firefox. Another route being considered is letting users run no browser at all, with the risk that some apps simply won't work because they rely on web pages internally."),

            ("h2", "How will drawbridge keep changing?"),
            ("p", "Depending on time, resources and technical obstacles, the following features are on the list:"),
            ("ul", [
                "Allowing YouTube, possibly with a filter",
                "Curfew: blocking internet access between set hours",
                "Blocking all video streaming (Netflix, Disney+, Prime, Veoh, ...)",
                "Whitelisting other browsers",
                "Blocking browsers entirely",
                "Allowing Telegram",
                "\"Dumbphone-ification\": only specific apps allowed. This can only work on selected devices, since every smartphone ships with different default apps.",
            ]),
        ],
    ),
    "nl": dict(
        title="Q&A — drawbridge",
        description="Veelgestelde vragen over drawbridge: wat wordt tegengehouden, voor wie is het, en hoe verhoudt het zich tot gewone parental controls.",
        h1="Q&A",
        blocks=[
            ("h2", "Welke apps en websites worden tegengehouden?"),
            ("p", "Voor het beschermen van je welzijn en je toestel, houdt drawbridge de volgende categorieën tegen: porno, gokken, oplichterij, algoritmische social media, AI companions, games met verslavende mechanismen of gevaar voor grooming. Over sommige social media bestaat discussie: bv. Reddit en Discord hebben een sterke communitywerking waar soms streng gemodereerd wordt, maar er blijft ook veel extreem gore content beschikbaar en toxische commentaren. In elk geval worden zo'n websites beter op een pc bezocht, er is geen enkele reden waarom je die moet meedragen in je zak."),
            ("p", "Alle andere websites en apps werken gewoon: tools, office, weerbericht, banking, publiek transport, school, werk, etc."),

            ("h2", "Voor wie is drawbridge?"),
            ("p", "Drawbridge is er voor iedereen die om een of andere reden een smartphone moet bijhebben maar via die smartphone geen ruimte of tijd wil geven aan schadelijke en verslavende apps en websites. Dat kunnen volwassenen zijn, voor zichzelf, of mensen die het toestel van een andere persoon beheren (bv. een kind)."),

            ("h2", "Waarom niet gewoon parental controls of een app blocker gebruiken?"),
            ("p", "Parental controls hebben veel nadelen:"),
            ("ul", [
                "Ze zijn moeilijk te configureren, en elke dag is er wel opnieuw werk aan om iets aan te passen",
                "Je moet expertise opbouwen in alles wat schadelijk is en alles wat kan geconfigureerd worden. Dat is gewoon tijdverlies.",
                "Ze zijn makkelijk te omzeilen, zelfs indien goed geconfigureerd.",
                "Het leidt tot discussie en conflict tussen ouder en kind, of in jezelf.",
                "Ze bespioneren de gebruiker en verzamelen mogelijks data.",
                "Ze zijn vaak niet gratis.",
            ]),
            ("p", 'Drawbridge maakt geen gebruik van parental controls maar is een device policy controller, zoals gebruikt voor bedrijfstelefoons en kiosken. In tegenstelling tot parental controls komt drawbridge out-of-the-box met een niet-configureerbare bescherming die reeds een zeer brede dekking geeft. Sociale media en schadelijke games worden altijd tegengehouden, geen discussie. Dat zorgt voor een omgeving met rust en zonder extra overhead. Besef dat drawbridge alleen niet voldoende is als "begeleiding van een kind online". Daar komt nog veel bij kijken, en bv. een best practice blijft het gebruik van internet op een gedeeld scherm, waar iedereen kan meekijken en discussiëren (niet voor privéconversaties, uiteraard).'),

            ("h2", "Hoe kan ik drawbridge uitschakelen of omzeilen?"),
            ("p", "Drawbridge heeft zowel een netwerkfilter als on-device filter en is daarom zo goed als waterdicht. Toch zijn er nog legio websites en apps die af en toe iets schadelijks zullen tonen. Aarzel niet om dit te melden. Het achterpoortje bij uitstek, de browser, is ook gedicht en drawbridge biedt een unieke ervaring aan om te browsen (zie verder)."),
            ("p", "Na het configureren van drawbridge wordt er een code getoond om de filter op te heffen en eventueel drawbridge te verwijderen. De code is random en te lang om zomaar op zicht te onthouden. De keuze is aan jou: schrijf de code op en steek ze veilig weg, of schrijf ze niet op en vergeet ze. Drawbridge blijft dan eeuwig actief."),
            ("p", "De enige andere manier, die ook geldig is voor doorsnee app blockers, is uiteraard een factory reset. Daarmee reset je het hele toestel en ben je ook je data kwijt. Het staat eigenlijk gelijk aan een nieuw toestel kopen. Maar toch: indien je het toestel beheert voor iemand anders, zoals je kind, en het toestel heeft een Google account, dan vereist de factory reset een Google paswoord. Dat is een beveiliging daartegen. De drawbridge app toont bovendien ook het moment van laatste activatie. Dat is een extra manuele controle om te zien of er niks werd gereset."),

            ("h2", "Wat met WhatsApp en andere chatapps?"),
            ("p", "Facebook Messenger en Telegram worden geblokkeerd. WhatsApp standaard ook, want die lijkt steeds meer op social media (kanalen, chatbot). Omdat WhatsApp voor veel mensen een noodzakelijk kwaad is (in sommige landen wordt zelfs niet meer conventioneel gebeld), kan je WhatsApp eventueel toch toestaan. Andere chatapps zoals Signal, Threema, Session, Briar etc. worden toegestaan, omdat versleutelde communicatie een mensenrecht is. Indien je het toestel geeft aan een kind, weet dat kinderen tot 14 jaar heel moeilijk om kunnen met groepschats en die zeer snel ontaarden in cyberpesten en drama."),

            ("h2", "Wat met YouTube?"),
            ("p", 'YouTube is eigenlijk social media. Hoewel de inhoud streng gemodereerd wordt op uitwassen zoals naaktheid, gokken en geweld, blijft er veel schadelijke of misleidende inhoud over. YouTube serveert alles op een zeer verslavende wijze, waarvoor Google reeds voor de rechtbank veroordeeld werd. Het schadelijkst van al zijn de YouTube Shorts, die men zeer moeilijk kan onderscheiden van de andere YouTube-filmpjes en waarop men niet kan filteren zonder privacyschending of foutgevoelige AI. Wegens de alomtegenwoordigheid van YouTube als "videotheek" met allerhande nuttige informatie (bv. tijdens het koken, het doe-het-zelven, ...) wordt er overwogen een toggle te maken zoals voor WhatsApp, onder voorbehoud.'),

            ("h2", "Waarom worden chatbots niet geblokkeerd?"),
            ("p", 'Reguliere chatbots, zoals ChatGPT, Claude of Gemini, kunnen inderdaad schadelijke effecten hebben op het brein bij overmatig gebruik en het vervangen van cognitief zware taken. Het is niet zo dat er verslavende mechanismen ingebouwd zijn, en net zoals met zoekmachines komen er steeds strengere guardrails wat te doen bij sommige soorten vragen. Het grootste probleem is echter de alomtegenwoordigheid van de chatbots: elke website of dienst heeft tegenwoordig wel een "assistent" waar je eigenlijk gelijk wat aan kan vragen. Indien je dit niet wil, dan gebruik je beter geen internet.'),

            ("h2", "Hoe zit het met de browser?"),
            ("p", 'De browser is traditioneel een achterpoortje waarlangs schadelijke inhoud je toestel en leven komt verzieken. Een aantal browsers of extensies zijn in staat een proxy of vpn om te zetten om zo de instellingen van het toestel (vaak met goede reden) te omzeilen. Drawbridge weigert daarom alle browsers behalve "herald". Herald is een browser speciaal gemaakt voor drawbridge maar die je ook apart kan downloaden, en blokkeert standaard dezelfde inhoud als drawbridge, out of the box, geen configuratie nodig. Een variatie, "herald mono", is een browser speciaal gemaakt voor digitaal minimalisme: het toont alle websites in zwart-wit, heeft geen tabs (singletasking), en opent alles in reader mode wanneer beschikbaar. Die laatste browser is vooral interessant voor mensen die vinden dat ze te veel tijd verliezen aan bv. nieuwswebsites of online shopping.'),
            ("p", "Onder voorbehoud is het idee om nog meer browsers op te nemen in de toegestane lijst, bij voorkeur ook een chromium-browser voor websites die op Firefox niet goed werken. Een andere piste is om gebruikers toe te staan helemaal geen browser te gebruiken, met de risico's dat bepaalde apps helemaal niet zullen werken omdat ze gebruikmaken van webpagina's."),

            ("h2", "Hoe gaat drawbridge nog veranderen in de toekomst?"),
            ("p", "Onder voorbehoud van tijd, middelen en technische obstakels, staan de volgende features op de lijst:"),
            ("ul", [
                "Toestaan van YouTube, eventueel met een filter",
                "Avondklok: blokkeren van internet tussen bepaalde uren",
                "Blokkeren van alle video streaming (Netflix, Disney+, Prime, Veoh, ...)",
                "Andere browsers whitelisten",
                "Browsers helemaal blokkeren",
                "Toestaan van Telegram",
                "Dumbphone-ificatie: enkel bepaalde apps worden toegestaan. Dit kan enkel werken bij geselecteerde toestellen, want elke smartphone komt met andere default apps.",
            ]),
        ],
    ),
    "fr": dict(
        title="Q&A — drawbridge",
        description="Questions fréquentes sur drawbridge : ce qui est bloqué, pour qui c'est fait, et en quoi cela diffère des contrôles parentaux classiques.",
        h1="Q&A",
        blocks=[
            ("h2", "Quelles applications et quels sites sont bloqués ?"),
            ("p", "Pour protéger votre bien-être et votre appareil, drawbridge bloque les catégories suivantes : pornographie, jeux d'argent, arnaques, réseaux sociaux algorithmiques, compagnons IA, et jeux aux mécanismes addictifs ou présentant un risque de grooming. Certains réseaux sociaux font débat : Reddit et Discord, par exemple, ont par endroits une forte modération communautaire, mais ils hébergent aussi encore beaucoup de contenu extrêmement violent et de commentaires toxiques. Dans tous les cas, ce genre de site se visite mieux sur un PC. Rien ne justifie de le transporter dans sa poche."),
            ("p", "Tout le reste fonctionne normalement : outils, bureautique, météo, banque, transports en commun, école, travail, etc."),

            ("h2", "Pour qui est drawbridge ?"),
            ("p", "Drawbridge s'adresse à toute personne qui doit, pour une raison ou une autre, avoir un smartphone sur soi, mais qui ne veut pas que ce téléphone laisse de la place ou du temps à des applications et des sites nuisibles et addictifs. Cela peut être un adulte qui se protège lui-même, ou une personne qui gère l'appareil de quelqu'un d'autre (un enfant, par exemple)."),

            ("h2", "Pourquoi ne pas simplement utiliser un contrôle parental ou un bloqueur d'applications ?"),
            ("p", "Les contrôles parentaux ont beaucoup d'inconvénients :"),
            ("ul", [
                "Ils sont difficiles à configurer, et il y a chaque jour un ajustement à refaire.",
                "Il faut se constituer une expertise sur tout ce qui est nuisible et sur tout ce qui peut être configuré. C'est simplement une perte de temps.",
                "Ils sont faciles à contourner, même bien configurés.",
                "Ils mènent à la discussion et au conflit, entre parent et enfant, ou avec soi-même.",
                "Ils espionnent l'utilisateur et peuvent collecter des données.",
                "Ils ne sont souvent pas gratuits.",
            ]),
            ("p", "Drawbridge n'utilise pas de contrôle parental, mais un device policy controller, comme ceux utilisés pour les téléphones d'entreprise et les bornes en libre-service. Contrairement aux contrôles parentaux, drawbridge offre d'emblée une protection non configurable qui couvre déjà un très large périmètre. Les réseaux sociaux et les jeux nuisibles sont toujours bloqués, sans discussion possible. Cela crée un environnement calme, sans charge de gestion supplémentaire. Sachez que drawbridge seul ne suffit pas comme « accompagnement d'un enfant en ligne » : cela demande bien plus, et une bonne pratique reste d'utiliser internet sur un écran partagé, où chacun peut voir et en discuter (pas pour les conversations privées, bien entendu)."),

            ("h2", "Comment désactiver ou contourner drawbridge ?"),
            ("p", "Drawbridge combine un filtre réseau et un filtre sur l'appareil, et est donc à peu près aussi étanche que possible. Il reste néanmoins de nombreux sites et applications qui montreront occasionnellement quelque chose de nuisible. N'hésitez pas à le signaler. La porte dérobée classique, le navigateur, est elle aussi verrouillée, et drawbridge propose sa propre manière de naviguer (voir plus loin)."),
            ("p", "Après la configuration de drawbridge, un code s'affiche pour lever le filtre et, le cas échéant, désinstaller drawbridge. Ce code est aléatoire et trop long pour être mémorisé d'un coup d'œil. Le choix vous appartient : notez-le et rangez-le en lieu sûr, ou ne le notez pas et oubliez-le, auquel cas drawbridge reste actif indéfiniment."),
            ("p", "L'autre seule issue, également valable pour les bloqueurs d'applications classiques, est bien sûr une réinitialisation aux paramètres d'usine. Cela réinitialise l'appareil entier et fait perdre vos données avec, ce qui revient en pratique à acheter un nouveau téléphone. Cela dit : si vous gérez l'appareil pour quelqu'un d'autre, comme votre enfant, et que l'appareil est lié à un compte Google, la réinitialisation exigera le mot de passe Google. C'est une protection prévue précisément contre cela. L'application drawbridge affiche en plus le moment de la dernière activation, un contrôle manuel supplémentaire pour vérifier que rien n'a été réinitialisé."),

            ("h2", "Qu'en est-il de WhatsApp et des autres applications de discussion ?"),
            ("p", "Facebook Messenger et Telegram sont bloqués. WhatsApp l'est aussi par défaut, car elle ressemble de plus en plus à un réseau social (chaînes, chatbot). Comme WhatsApp est, pour beaucoup de gens, un mal nécessaire (dans certains pays, on ne s'appelle quasiment plus de façon classique), vous pouvez malgré tout choisir de l'autoriser. D'autres applications de discussion comme Signal, Threema, Session, Briar, etc. sont autorisées, car la communication chiffrée est un droit humain. Si vous confiez l'appareil à un enfant, sachez que les enfants de moins de 14 ans gèrent très difficilement les discussions de groupe, qui dégénèrent très vite en cyberharcèlement et en drames."),

            ("h2", "Qu'en est-il de YouTube ?"),
            ("p", "YouTube est, dans les faits, un réseau social. Bien que son contenu soit strictement modéré contre les excès comme la nudité, les jeux d'argent et la violence, il reste beaucoup de contenu nuisible ou trompeur. YouTube diffuse tout d'une manière hautement addictive, ce pour quoi Google a déjà été condamné en justice. Le plus nuisible de tous reste YouTube Shorts, très difficile à distinguer des autres vidéos YouTube et impossible à filtrer sans porter atteinte à la vie privée ou recourir à une IA sujette à erreur. En raison de l'omniprésence de YouTube comme « vidéothèque » regorgeant d'informations réellement utiles (par exemple pour cuisiner ou bricoler), l'ajout d'un interrupteur similaire à celui de WhatsApp est envisagé, sans que ce soit décidé."),

            ("h2", "Pourquoi les chatbots ne sont-ils pas bloqués ?"),
            ("p", "Les chatbots classiques, comme ChatGPT, Claude ou Gemini, peuvent effectivement avoir des effets nuisibles sur le cerveau en cas d'usage excessif et en remplaçant des tâches cognitivement exigeantes. Ils ne comportent pas de mécanismes construits pour rendre dépendant, et, tout comme pour les moteurs de recherche, des garde-fous de plus en plus stricts apparaissent pour certains types de questions. Le problème principal est plutôt l'omniprésence des chatbots : presque chaque site ou service dispose aujourd'hui d'un « assistant » à qui l'on peut à peu près tout demander. Si vous ne le voulez pas, la réponse honnête est de ne pas utiliser internet du tout."),

            ("h2", "Qu'en est-il du navigateur ?"),
            ("p", "Le navigateur est traditionnellement la porte dérobée par laquelle le contenu nuisible s'invite sur votre appareil et dans votre vie. Certains navigateurs ou extensions sont capables de configurer un proxy ou un VPN, précisément pour contourner les réglages de l'appareil (souvent pour de bonnes raisons ailleurs, mais pas ici). Drawbridge refuse donc tous les navigateurs sauf « herald ». Herald est un navigateur conçu spécialement pour drawbridge, mais peut aussi être téléchargé séparément, et bloque par défaut le même contenu que drawbridge, d'emblée, sans configuration nécessaire. Une variante, « herald mono », est un navigateur conçu spécialement pour le minimalisme numérique : il affiche tous les sites en noir et blanc, n'a pas d'onglets (une seule tâche à la fois), et ouvre tout en mode lecture lorsque c'est possible. Ce second navigateur intéresse surtout les personnes qui estiment perdre trop de temps sur, par exemple, les sites d'actualité ou les achats en ligne."),
            ("p", "L'ajout d'autres navigateurs à la liste autorisée est envisagé, sans être décidé, idéalement avec un navigateur basé sur Chromium pour les sites qui fonctionnent mal sous Firefox. Une autre piste envisagée est de permettre aux utilisateurs de n'utiliser aucun navigateur du tout, au risque que certaines applications ne fonctionnent plus du tout parce qu'elles s'appuient en interne sur des pages web."),

            ("h2", "Comment drawbridge va-t-il encore évoluer ?"),
            ("p", "Selon le temps, les moyens et les obstacles techniques disponibles, les fonctionnalités suivantes sont envisagées :"),
            ("ul", [
                "Autoriser YouTube, éventuellement avec un filtre",
                "Couvre-feu : blocage d'internet entre certaines heures",
                "Blocage de tout le streaming vidéo (Netflix, Disney+, Prime, Veoh, ...)",
                "Autoriser d'autres navigateurs (liste blanche)",
                "Bloquer complètement les navigateurs",
                "Autoriser Telegram",
                "« Dumbphone-ification » : seules certaines applications seraient autorisées. Cela ne peut fonctionner que sur des appareils sélectionnés, car chaque smartphone est livré avec des applications par défaut différentes.",
            ]),
        ],
    ),
}


def render_faq(lang: str) -> str:
    c = FAQ[lang]
    parts = []
    for kind, payload in c["blocks"]:
        if kind == "h2":
            parts.append(f"<h2>{payload}</h2>")
        elif kind == "p":
            parts.append(f"<p>{payload}</p>")
        elif kind == "ul":
            items = "\n".join(f"<li>{item}</li>" for item in payload)
            parts.append(f"<ul>\n{items}\n</ul>")
    body = f"""
  <section class="section">
    <div class="wrap">
      <h1>{c['h1']}</h1>
      {chr(10).join(parts)}
    </div>
  </section>
"""
    return render_page(lang=lang, path="faq/", title=c["title"], description=c["description"], body=body)


# ---------------------------------------------------------------------------
# Why-blocked. The full cited list is English only, deliberately — around 200
# rows of legal and clinical claims across jurisdictions, not something to
# machine-translate without review, and expected to keep evolving rather than
# settle into something worth maintaining in three languages. See
# convert_blocklist.py for the markdown → HTML conversion.
#
# Dutch and French get a short summary page at the same path instead, ending
# in a link to the English original. That exists because the homepage and
# install page both link here with a language prefix: without these pages
# those links 404, which is worse than a summary that admits its own limits.
# ---------------------------------------------------------------------------

WHY_TITLE = "The blocklist and the why — drawbridge"
WHY_DESCRIPTION = "The evidence behind every category and app drawbridge blocks: official ratings, independent reviews, regulator findings and cited research."

WHY_SUMMARY = {
    "nl": dict(
        title="Wat wordt geblokkeerd, en waarom — drawbridge",
        description="Een korte samenvatting van wat drawbridge tegenhoudt en op welke basis, met een link naar de volledige lijst met bronnen.",
        h1="Wat wordt geblokkeerd, en waarom",
        paragraphs=[
            "Drawbridge houdt zes categorieën tegen: pornografie, gokken, oplichterij, algoritmische social media, AI companions, en games met verslavende mechanismen of een risico op grooming. Al de rest blijft gewoon werken — gereedschap, kantoorsoftware, weerbericht, bankieren, openbaar vervoer, school en werk. De lijst is niet configureerbaar: dat is precies het punt, want elke instelling die je zelf kan aanpassen is er ook één waarover discussie mogelijk is.",
            "Elke keuze op de lijst steunt op openbare bronnen: officiële leeftijdslabels (PEGI, ESRB), onafhankelijke beoordelingen zoals Common Sense Media, uitspraken van toezichthouders zoals de Belgische Kansspelcommissie, de Europese Commissie en de Australische eSafety Commissioner, en richtlijnen van medische en kinderpsychiatrische organisaties zoals AACAP, de APA en de WHO. Wat daarbij het vaakst terugkomt: het officiële leeftijdslabel in de winkel ligt vaak jaren lager dan wat onafhankelijke beoordelaars aanraden, en het label zegt bovendien niets over chatfuncties met vreemden of over betaalde willekeurige beloningen.",
        ],
        cta="Lees de volledige lijst met alle bronnen (Engels)",
    ),
    "fr": dict(
        title="Ce qui est bloqué, et pourquoi — drawbridge",
        description="Un résumé de ce que drawbridge bloque et sur quelles bases, avec un lien vers la liste complète et ses sources.",
        h1="Ce qui est bloqué, et pourquoi",
        paragraphs=[
            "Drawbridge bloque six catégories : la pornographie, les jeux d'argent, les arnaques, les réseaux sociaux algorithmiques, les compagnons IA, et les jeux aux mécanismes addictifs ou présentant un risque de grooming. Tout le reste continue de fonctionner normalement : outils, bureautique, météo, banque, transports en commun, école et travail. La liste n'est pas configurable, et c'est précisément l'intérêt : tout réglage que l'on peut modifier soi-même est aussi un réglage dont on peut débattre.",
            "Chaque entrée de la liste s'appuie sur des sources publiques : les classifications officielles par âge (PEGI, ESRB), des évaluations indépendantes comme Common Sense Media, des décisions de régulateurs comme la Commission belge des jeux de hasard, la Commission européenne et l'eSafety Commissioner australien, ainsi que les recommandations d'organisations médicales et pédopsychiatriques comme l'AACAP, l'APA et l'OMS. Le constat qui revient le plus souvent : l'âge affiché sur la boutique est souvent inférieur de plusieurs années à ce que recommandent les évaluateurs indépendants, et il ne dit rien des fonctions de discussion avec des inconnus ni des récompenses aléatoires payantes.",
        ],
        cta="Lire la liste complète avec toutes les sources (en anglais)",
    ),
}


def render_why_summary(lang: str) -> str:
    c = WHY_SUMMARY[lang]
    paragraphs = "\n      ".join(f"<p>{p}</p>" for p in c["paragraphs"])
    body = f"""
  <section class="section">
    <div class="wrap">
      <h1>{c['h1']}</h1>
      {paragraphs}
      <div class="btn-row">
        <a class="btn btn--primary" href="/why-blocked/">{c['cta']}</a>
      </div>
    </div>
  </section>
"""
    return render_page(
        lang=lang,
        path="why-blocked/",
        title=c["title"],
        description=c["description"],
        body=body,
    )


def render_why_blocked(content_fragment: str) -> str:
    body = f"""
  <section class="section">
    <div class="wrap wrap--wide">
{content_fragment}
    </div>
  </section>
"""
    return render_page(
        lang="en",
        path="why-blocked/",
        title=WHY_TITLE,
        description=WHY_DESCRIPTION,
        body=body,
    )


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

def write(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def build_all() -> None:
    if SITE_OUT.exists():
        for item in SITE_OUT.iterdir():
            if item.name == "assets":
                continue
            if item.is_dir():
                shutil.rmtree(item)
            else:
                item.unlink()

    import sys
    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
    import convert_blocklist  # tools/convert_blocklist.py
    why_fragment = convert_blocklist.build_fragment()
    write(SITE_OUT / "why-blocked" / "index.html", render_why_blocked(why_fragment))

    for lang in LANGUAGES:
        base = SITE_OUT if lang == "en" else SITE_OUT / lang
        write(base / "index.html", render_home(lang))
        write(base / "install" / "index.html", render_install(lang))
        write(base / "faq" / "index.html", render_faq(lang))
        if lang in WHY_SUMMARY:
            write(base / "why-blocked" / "index.html", render_why_summary(lang))

    check_internal_links()
    print(f"Built {len(LANGUAGES)} languages into {SITE_OUT}")


def check_internal_links() -> None:
    """Fails the build on a site-internal link with no file behind it.

    Added after the homepage and install page shipped pointing at
    /nl/why-blocked/ and /fr/why-blocked/, which did not exist: the nav had
    been special-cased to the English URL but the in-page buttons had not.
    A 404 in generated output is exactly the kind of thing a generator
    should catch rather than a person.
    """
    import re

    broken: list[str] = []
    for page in sorted(SITE_OUT.rglob("*.html")):
        html = page.read_text(encoding="utf-8")
        for href in re.findall(r'href="(/[^"#]*)"', html):
            target = SITE_OUT / href.lstrip("/")
            if target.suffix:           # a file, e.g. /assets/css/style.css
                ok = target.exists()
            else:                       # a directory URL, e.g. /nl/faq/
                ok = (target / "index.html").exists()
            if not ok:
                broken.append(f"{page.relative_to(SITE_OUT)} -> {href}")

    if broken:
        raise SystemExit(
            "Broken internal links:\n  " + "\n  ".join(broken)
        )


if __name__ == "__main__":
    build_all()
